spring:
  application:
    name: ReaTimeCommunicationService
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18375

  redis:
    database: 0
    host: localhost
    port: 6379

    lettuce:
      pool:
        min-idle: 4
        max-idle: 8
        max-active: 8
        max-wait: -1ms

server:
  port: 8083
netty:
  port: 9000